name: 'Post Amazon Cloudwatch Metrics'
description: 'Publishes a metric to Amazon CloudWatch.'
author: 'ROS Tooling Working Group'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  metric-name:
    description: 'Name of the metric to be published'
    default: 'Builds'

  metric-value:
    description: >-
      Value of the metric to be published

      true, and false are respectfully converted to 1.0, and 0.0 automatically
    default: "${{ job.status == 'success' }}"

  metric-dimensions:
    description: 'Dimension of the metric to be published, as a JSON object'
    default: >-
      [
        { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
        { "Name": "github.ref", "Value": "${{ github.ref }}" },
        { "Name": "github.repository", "Value": "${{ github.repository }}" }
      ]
  metric-data:
    description: >-
      Path to a JSON file containing CloudWatch-compatible metrics, according to
      https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudwatch/put-metric-data.html
      If this input is specified, the action will ignore the single-value inputs "metric-name", "metric-value", "metric-dimensions" and only publish the data from this file.
    required: false

  namespace:
    description: 'The namespace for the metric data.'
    default: 'ActionCloudWatchMetrics'

runs:
  using: 'node12'
  main: 'dist/index.js'
